ContactProj/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('contactapp.urls', namespace='contactapp'))
]

contactapp/urls.py
from django.urls import path,URLPattern
from . import views
from django.conf import settings
from django.conf.urls.static import static 
# from .views import *

app_name='contactapp'


urlpatterns=[
    path('',views.homepage,name='homepage'),
    # path('contact_list',views.contact_list,name='contact_list'),
    path('contact_list/<int:pk>/',views.contact_detail.as_view(),name='contact_detail'),
    path('contact_list/',views.contact_list,name='contact_list'),
    path('update/<int:pk>/',views.contact_edit,name='update'), ### Doubt ##
    path('delete/<int:pk>/',views.contact_delete,name='delete'),
    #path('<pk>/',views.contact_detail.as_view(),name='contact_detail'),
    path('create/',views.contact_new,name='create'),
]

if settings.DEBUG: 
        urlpatterns += static(settings.MEDIA_URL, 
                              document_root=settings.MEDIA_ROOT) 

contactapp/models.py
from django.db import models
# from phonenumber_field.modelfields import PhoneNumberField
from django.utils import timezone
from django.urls import reverse

class Person(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    email = models.EmailField(max_length=20)
    profile_pic=models.ImageField(upload_to='contact_pic',blank=True)
    # phonenumber = PhoneNumberField(blank=True)
    phonenumber=models.CharField(max_length=10)
    def publish(self):
        self.published_date = timezone.now()
        self.save()
    def full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)
    def __str__(self):
        return self.full_name()
    def get_absolute_url(self):
        return reverse("contactapp:contact_detail",kwargs={'pk':self.pk})

contactapp/forms.py
from django import forms
from .models import Person
class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ('first_name', 'last_name', 'email', 'phonenumber','profile_pic')

contactapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Person
from . import models
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
# from .forms import PersonForm 
from . import forms

def homepage(request):
    return render(request,'contactapp/homepage.html')


def contact_list(request):
    persons = Person.objects.all().order_by('first_name')
    return render(request, 'contactapp/contact_list.html', {'persons': persons})

def contact_new(request):
    if request.method == 'POST':
        form = forms.PersonForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/')
    else:
        form = forms.PersonForm()
    return render(request, 'contactapp/contact_edit.html', {'form': form})

class contact_detail(DetailView):
    context_object_name = 'contactdetails'
    model = models.Person
    template_name = 'contactapp/contact_detail.html'
    
def contact_edit(request, pk):
    person = get_object_or_404(models.Person, pk=pk)
    if request.method == 'POST':
        form = forms.PersonForm(request.POST, instance=person)
        if form.is_valid():
            form.save()
            # return redirect('/person/' + str(person.pk))
            return redirect('/')        ### You have to change this !!!! ##### Take them to contact list !!
    else:
        form = forms.PersonForm(instance=person)
    return render(request, 'contactapp/contact_edit.html', {'form': form})

def contact_delete(request, pk):
    person = get_object_or_404(models.Person, pk=pk)
    person.delete()
    return redirect('/')

contactapp/templates/contactapp/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Contact</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
      <script src='https://kit.fontawesome.com/a076d05399.js'></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
        <a class="navbar-brand" href={% url 'admin:index' %}>Admin</a>
        <div class="navbar-nav align-items-right justify-content-end">
            {% if user.is_authenticated %}
                <a href={% url 'contactapp:contact_list' %} style="color: azure;" class="navbar-brand nav-link">Contact_List</a>
            {% endif %}
        
        </div>
    </nav>
    <!-- <div class="navbar-nav align-items-right justify-content-end">

    </div> -->
    <div class="container">
    {% block content %}

    {% endblock %}

    </div>

</body>
</html>

contactapp/templates/contactapp/contact_detail.html
{% extends "contactapp/base.html" %}
    {% block content %}

    <div class="conatiner" style="padding-top: 90px;">
        <div class="jumbotron">
            <h2>Contact details:</h2><br>
            <h5>First Name: {{ contactdetails.first_name }} </h5>
            <h5>Last Name: {{ contactdetails.last_name }}</h5>
            <h5>Email: {{ contactdetails.email }}</h5>
            <h5>Phone Number: {{ contactdetails.phonenumber }}</h5><br>
            
            <!-- {% if contactdetails.profile_pic %}
              
              <img src="{{ contactdetails.profile_pic.url }}" style="width: 700px;padding-bottom: 10px;border-radius: 50%;" />
            {% endif %} -->
              
            
            
              
            
            <!-- <p style="padding-left: 20px;"><a class="btn btn-primary" href={% url 'contactapp:update' pk=contactdetails.pk %} role="button">Update</a></p>
            <p style="padding-left: 40px;"><a class="btn btn-primary" href={% url 'contactapp:delete' pk=contactdetails.pk %} role="button">Delete</a></p> -->
            
            <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
                <div class="btn-group mr-2" role="group" aria-label="First group">
                  <button type="button" class="btn btn-secondary"><a href={% url 'contactapp:update' pk=contactdetails.pk %} style="color: azure;">Update</a></button>
                </div>
                <div class="btn-group mr-2" role="group" aria-label="Second group">
                  <button type="button" class="btn btn-secondary"><a href={% url 'contactapp:delete' pk=contactdetails.pk %} style="color: azure;">Delete</a></button>
                </div>
              </div>
        </div>
    </div>
    
    
    {% endblock %}

contactapp/templates/contactapp/contact_edit.html
{% extends "contactapp/base.html" %}
{% load bootstrap4 %}
{% block content %}
<div class="container">
    <form method="post" class="form1" enctype="multipart/form-data">
        {% csrf_token %}
        <!-- <div class="form1">
        {{ form.as_p }}
        </div> -->
        {% bootstrap_form form %}
        <input class="btn btn-primary" type="submit" value="Save" />
    </form>
</div>
{% endblock %}

contactapp/templates/contactapp/contact_list.html
{% extends "contactapp/base.html" %}
    {% block content %}

    <h1>Welcome to Contact App <span class="material-icons">sentiment_very_satisfied</span></h1> <br> <!--<h1>We are happy to have you here :] </h1>-->
    <br>
    <div class="center" style="border:2px solid black;padding: 10px 10px;">
    {% if user.is_authenticated %}
    <h2>Here's the list of your Contacts: </h2>
    <div>
        {% for person in persons %}
            <ul>
                <li><a href="{{person.id}}" style="color: blue;font-size: 2em;">{{ person.full_name }}</a></li>
            </ul>
        {% endfor %}
        <br>
        <p style="padding-left: 20px;"><a class="btn btn-primary" href={% url 'contactapp:create' %} role="button"><span class="material-icons">
            person_add
            </span></a></p>
    </div>
    {% else %}
    <div class="conatainer" style="margin: auto;text-align: center;display: inline-block;">
        <h4>No contacts to show :) </h4>
        <h4>But we got you covered ! You can create them too.. </h4>
        <h4> Please check if you are logged in :) </h4>
    </div>
    {% endif %}
    
    </div>
    

    {% endblock %}

contactapp/templates/contactapp/homepage.html
{% extends "contactapp/base.html" %}
    {% block content %}

    <h1>Welcome to home page !</h1>
    <br>
    {% if user.is_authenticated %}
    <h2>Yayy you are logged in !</h2>
    <h2>Check out your contacts using the Contact List in navbar :D </h2>
    {% else %}
    <h2>Please Login first !</h2>
    <h2>You have to be a superuser for logging in. </h2>
    {% endif %}
    {% endblock %}